### ISSUE TITLE
sending to devices tuples, named tuples and arrays does not keep track of identical objects

### ISSUE THREAD

**Issue by CarloLucibello** [LuxDL/Lux.jl#1017]
The issue has been reported in 
https://github.com/FluxML/Flux.jl/issues/2513
and is due to these specializations
https://github.com/LuxDL/MLDataDevices.jl/blob/17419d27888e3a48b52f318249a0f037524f0f1e/src/public.jl#L341
The simplest solution would be to remove the specializations and let `fmap` handle everything.

Possible optimized implementations could be upstreamed to Functors.jl, but we really want to keep track of object identity here.

**Comment by CarloLucibello** [comment]
Why the repo has been archived?

**Comment by CarloLucibello** [comment]
With https://github.com/FluxML/Functors.jl/pull/82 `fmap` is type stable for all types

**Comment by avik-pal** [comment]
Let's do it together with updating functors to v0.5.
