### ISSUE TITLE
`getkeypath` and `layer_map` not fully working with model with `Parallel` layers

### ISSUE THREAD

**Issue by dmetivie** [LuxDL/Lux.jl#1068]
Trying the example of `layer_map` [here](https://lux.csail.mit.edu/stable/api/Lux/contrib#Map-over-Layer), I wonder how to get back a specific layer given a `KeyPath`. 
In the example doing on the parameters `ps`
```julia
getkeypath(ps, KeyPath(:chain, :dense_1))
```
works, however, with the model `c` it does not work
```julia
getkeypath(c, KeyPath(:chain, :dense_1))
ERROR: type Parallel has no field chain
```

I wondered if you intended this to work (as it would be very convenient to target specific layer and get parameters (with `ps`) or types (with `c`).
Note that doing
```julia
getkeypath(c.layers, KeyPath(:chain, :dense_1))
ERROR: type Parallel has no field chain
```
works and on regular layers too.
It looks like a dispatch like `getkeypath(c::Lux.Parallel, kp) = getkeypath(c.layers, kp)` could do the job (however it does not work directly).

**Comment by dmetivie** [comment]
Another issue I think is related as keys of layer and ps are treated differently is that `layer_map` fails with `MaxPool` layers.
Using the chain from [MNIST tuto](https://lux.csail.mit.edu/stable/tutorials/beginner/4_SimpleChains#Define-the-Model)
```
c = Chain(Conv((5, 5), 1 => 6, relu), MaxPool((2, 2)),
    Conv((5, 5), 6 => 16, relu), MaxPool((2, 2)), FlattenLayer(3),
    Chain(Dense(256 => 128, relu), Dense(128 => 84, relu), Dense(84 => 10)))
ERROR: ArgumentError: keys(layer_children) == keys(ps_children) must hold. Got
keys(layer_children) => Base.OneTo(0)
keys(ps_children) => ()
```

**Comment by avik-pal** [comment]
This is mostly by design of `AbstractLuxWrapperLayer`. See https://github.com/LuxDL/Lux.jl/blob/bbf503374b42432324654d4701d284fa5bac74f3/src/contrib/map.jl#L67-L80 for how we do the traversal.

That said can you tell about your specific usecase? If you are trying to debug something then https://lux.csail.mit.edu/stable/api/Lux/contrib#Lux.Experimental.@debug_mode should print out the exact path. As for layer_map the layer, ps and st are already available directly to the input function

**Comment by avik-pal** [comment]
> To me, it looks like a bug that the layer_map errors with MaxPool layers.

I would agree, pooling layers are implemented slightly differently, so this is possible. I will dig into this.

> BTW I don't know where to put this layer (probably to specific to directly put in Lux.jl)

https://github.com/LuxDL/Boltz.jl is exactly the repo for these forms of layers

> I implemented the CD layer, however in the original implementation they add a regularization term in the loss that depends on

Would it be possible to implement this as a AbstractLuxWrapperLayer over a Conv/Dense similar to how WeightNorm is implemented?

**Comment by dmetivie** [comment]
Thanks. Note that `@debug_mode` also fails with `MaxPool` layers.

Ok I'll try PR to Boltz when I succeed. 
I see how `AbstractLuxWrapperLayer` can do the Concrete Dropout layers, however there is still the issue of **automatically** extracting the weights and dropout rate for the penalization.

**Comment by avik-pal** [comment]
`layer_map` and `@debug_mode` should work with pooling layers after https://github.com/LuxDL/Lux.jl/pull/1115
