### ISSUE TITLE
[AMDGPU CI] Circular dependencies disabling precompilation

### ISSUE THREAD

**Issue by pxl-th** [LuxDL/Lux.jl#1095]
Not sure if this is the main cause of huge CI execution time, but there are a **lot** of circular dependencies detected:
https://buildkite.com/julialang/lux-dot-jl/builds/4941#0193462a-9ae9-4371-a067-d20253b0022d

Linked CI job will take 9+ hours to complete (9/94 items completed in ~1 hour).
Not sure what's exactly causing a circular dependency

**Comment by avik-pal** [comment]
I think it is precompilation that is causing this. The CI time should be between 50 mins-1.5hr

**Comment by avik-pal** [comment]
I can reproduce by just having Tracker + AMDGPU in a fresh env

**Comment by avik-pal** [comment]
I tracked it down to AMDGPU 1.0.5 which adds AcceleratedKernels as a maindep

**Comment by pxl-th** [comment]
Digging deeper, it is caused by Polyester dependency in AcceleratedKernels.
Probably one of its dependencies messes things up

**Comment by pxl-th** [comment]
StaticArrayInterface in Polyester is causing this.

**Comment by avik-pal** [comment]
CI time is now down to the original times
