### ISSUE TITLE
`(AbstractDevice)(x)` should respect `Adapt.adapt_structure`

### ISSUE THREAD

**Issue by vpuri3** [LuxDL/Lux.jl#1149]
The current implementation of `cpu_device()(x)` does not work if `x`, say, has an abstract FFT plan. Rather, it should call `adapt_storage` on `x` if that is defined.

https://github.com/LuxDL/Lux.jl/blob/main/lib/MLDataDevices/src/public.jl#L366

**Comment by avik-pal** [comment]
The issue with `Adapt.adapt_structure` is that it is opt-in and has very few structures defined.

**Comment by vpuri3** [comment]
would you recommend overloading `device(x)` for types that may also overload `Adapt.adapt_strucure`?

**Comment by vpuri3** [comment]
the issue with the functor implementation is that adapt_structure is applied to leaf elements of x. so if i want a custom conversion for x.a, that won't be possible if x.a has subfields.

the adapt approach is preferable for overloading as the conversion of x.a.b would be handled by the recursive adapt call to x.a.

**Comment by avik-pal** [comment]
Mark `x.a` as a `MLDataDevices.isleaf` or a `Functors.isleaf`?

**Comment by vpuri3** [comment]
Thanks, let me try that.

**Comment by vpuri3** [comment]
Thanks Avik, that did work.
