### ISSUE TITLE
Adding `AbstractRecurrentCell`

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [LuxDL/Lux.jl#320]
I was reading through `recurrent.jl` and sqw the [comment](https://github.com/LuxDL/Lux.jl/blob/main/src/layers/recurrent.jl#L1) about adding another subtype for dispatching over `Recurrence` and `StatefulRecurrentCell` more safely. Would something along the lines of 
```julia
abstract type AbstractRecurrentCell{use_bias, train_state} <: 
    AbstractExplicitLayer end

struct Recurrence{R, C <: AbstractRecurrentCell} <: 
    AbstractExplicitContainerLayer{(:cell,)}
    cell::C
end

struct StatefulRecurrentCell{C <: AbstractRecurrentCell} <:
       AbstractExplicitContainerLayer{(:cell,)}
    cell::C
end

struct RNNCell{use_bias, train_state, A, B, W, S} <: AbstractRecurrentCell{use_bias, train_state}
    activation::A
    in_dims::Int
    out_dims::Int
    init_bias::B
    init_weight::W
    init_state::S
end

etcetc...
```
be fine or did you have a more specific design in mind?

**Comment by avik-pal** [comment]
Yes, this is pretty much what I had in mind

**Comment by MartinuzziFrancesco** [comment]
Very nice, I should have some code in place already! I'll open a PR
