### ISSUE TITLE
Include documentation on how to save models with Lux

### ISSUE THREAD

**Issue by user161715** [LuxDL/Lux.jl#329]
Hello,

I would like to know how to save and load a neural network model with `Lux`. Would you consider introducing this information into the documentation. 

For instance in the example [Fitting a Polynomial using MLP](https://lux.csail.mit.edu/stable/examples/generated/beginner/PolynomialFitting/main/). How can you save and load the trained network?

Best regards

**Comment by prbzrg** [comment]
To save any variable, including a `Dict` of variables; you can use `JLD2`
https://github.com/JuliaIO/JLD2.jl

**Comment by prbzrg** [comment]
AFAIK, architecture doesn't need to be stored. As well as initial parameters.

**Comment by avik-pal** [comment]
Correct, saving architecture is possible but is not recommended. `Parameter` and `State` loading is backward compatible, but model architecture loading is not. So I would never save the model architecture, and for some reason, if you *really* need to save it, do so in a separate file.

```julia
save("myNetwork_parameter_states.jld2",
     "states", st,
     "trained_parameters" , p_trained
    )

save("myNetwork_architecture.jld2",
     "neural_network", U,
    )
```

Also, you don't need to save the initial parameters unless you want to reproduce training later on.
