### ISSUE TITLE
Working with NamedTuples 

### ISSUE THREAD

**Issue by ordicker** [LuxDL/Lux.jl#331]
Hi, 

First of all, great package! I'm playing with NN ideas and this package is by far the most flexible. 

I'm trying to add some random noise to the weights, and I'm sure how to do it. 
On the CPU, I can use `ComponentArray` and then it is straight forward, but then the code doesn't run on the GPU. 

I tried something like this:
```julia
using Lux, Random, NNlib, CUDA
using Functors: fmap

rng = MersenneTwister()
Random.seed!(rng, 12345)

model = Chain(Dense(1 => 16, relu), Dense(16 => 1))
ps, st = Lux.setup(rng, model)|>gpu

fmap(x->x.+CUDA.rand(eltype(x),size(x)),ps)
```
Is this the way to go? Is there a better way?

**Comment by avik-pal** [comment]
```julia
using Lux, Random, NNlib, CUDA, ComponentArrays
using Functors: fmap

rng = MersenneTwister()
Random.seed!(rng, 12345)

model = Chain(Dense(1 => 16, relu), Dense(16 => 1))
ps, st = Lux.setup(rng, model)
ps = ComponentArray(ps) |> gpu

ps = ps .+ rand!(similar(ps))
```

**Comment by ordicker** [comment]
Thanks for the fast response. 

I'm trying to add noise in the gradient step so the `ps` is already `NameTuple` on the gpu.

```julia 
ps, st = Lux.setup(rng, model)|>gpu
ps = ComponentArray(ps)
```
That doesn't work :( 

more exact example looks like this: 
```julia
function compute_gradients(vjp::ESG, objective_function::Function, data, ts::TrainState)
    θ = ts.parameters
    <some simple calculation on θ> 
    ...
```
Here, the `data` and `ts.parameters` is already on the gpu (the code works on the cpu). 
I think it's relate to this [problem](https://github.com/LuxDL/Lux.jl/pull/109#discussion_r933909078)

So my question is, can I do simple manipulation on `ts.parameters` (on the gpu) without `ComponentArray`?

**Comment by avik-pal** [comment]
Instead of doing `fmap(x->x.+CUDA.rand(eltype(x),size(x)),ps)` you could do `fmap(x->x.+rand!(similar(x)),ps)` then the code would be hardware agnostic.

**Comment by ordicker** [comment]
Thanks!
