### ISSUE TITLE
Add ability to load weights into `Dense`

### ISSUE THREAD

**Issue by AnasAbdelR** [LuxDL/Lux.jl#361]
I was searching through the documentation and noticed that there is no function call to load a `Dense` layer with weights? i.e 

```julia
W = rand(10,10)
layer = Dense(W)
```

I am trying to take some model I had previously trained using `Flux.jl` and load it into a `Lux.jl` `Dense` layer. Is there a way to do this currently?

**Comment by avik-pal** [comment]
Lux is parameter/stateless so Dense in principle you can't directly load it. But an easy workaround (unless you want to directly deal with NamedTuples) is to specify `init_weight`. See https://github.com/LuxDL/Lux.jl/blob/ad2655a9acf72e7a5b863ffeba57440a5c9128dc/ext/LuxFluxTransformExt.jl#L68.

If you have a pretrained Flux model try using https://lux.csail.mit.edu/dev/api/flux2lux/#Lux.transform.
