### ISSUE TITLE
Initialize weights of network from csv file

### ISSUE THREAD

**Issue by tpjerry** [LuxDL/Lux.jl#369]
Hi,

I have the structure of a neural network.
I have the weights and biases of each layer in a .csv file.

As an example:
```
rng = StableRNG(1111); 
U = Lux.Chain(Lux.Dense(2, 3, Lux.tanh), 
              Lux.Dense(3, 2));

p, st = Lux.setup(rng, U) 
```

.csv file:
```
w1	w2	b
1	2	3
4	5	6
7	8	9
```

I can read the data with:
```
using DataFrames, CSV
data = CSV.read("data.txt", DataFrame);
```

But if I assign the `data` to a layer I get an `immutable struct`... error: 
`p[1].weight = Matrix{Float32}(data[:, 1:3])`

How can I initialize the weights and biases of the network with data from a file?

Best Regards

**Comment by tpjerry** [comment]
I think, I was able to do it with 

```
function l1_weights(rng, dims::Integer...)
        return Matrix{Float32}(data[:,1:end-1])
end
```

```
function l1_bias(rng, dims::Integer...)
        return reshape(Vector{Float32}(data[:,end]), (3,1))
end
```

```
U = Lux.Chain(Lux.Dense(2, 3, Lux.tanh, init_weight = l1_weights, init_bias =l1_bias), 
              Lux.Dense(3, 2));
```

**Comment by avik-pal** [comment]
The way you suggested is one way to do it. The neater way IMO is to use `SetField.jl`.

```julia
using SetField

@set! p[1].weight = Matrix{Float32}(data[:, 1:3])
```

**Comment by tpjerry** [comment]
Thanks! 
Is this in the documentation?
