### ISSUE TITLE
DocumenterVitepress module into package 

### ISSUE THREAD

**Issue by lazarusA** [LuxDL/Lux.jl#385]
A lot of good work is in this module, maybe putting it into an independent package for easier an maintenance would be a good move?

**Comment by avik-pal** [comment]
That is the plan (even I want to use vitepress for some of my other non-Lux packages).

There are a few quirks described in https://github.com/LuxDL/Lux.jl/issues/387 (not very hard to patch, though) which need fixing before releasing an independent package.

**Comment by lazarusA** [comment]
Hi, it looks like things are at the stage where having an independent package maybe worth it? I could do one, if that helps speeding up the process, although you did all the coding, so, I would rather not 😄 .

**Comment by avik-pal** [comment]
Feel free to do it, I can create an empty repo under LuxDL and give you push access. It was mostly a minor patch over DocumenterMarkdown. (It might even be worth to check the diff and see if we should push it there)

**Comment by lazarusA** [comment]
> I can create an empty repo under LuxDL and give you push access.

Yes, that would be great. Thanks.

**Comment by avik-pal** [comment]
A repo now exists so closing this https://github.com/LuxDL/DocumenterVitepress.jl. Discussions can be done there itself. Thanks @lazarusA  for taking charge!!
