### ISSUE TITLE
Documentation Enhancement Suggestions

### ISSUE THREAD

**Issue by avik-pal** [LuxDL/Lux.jl#387]
Taken from https://discourse.julialang.org/t/ann-lux-jl-explicitly-parameterized-neural-networks-in-julia/81689/21

- [x] Update Downstream Packages to use vitepress syntax in documentation
  - [x] LuxCore
  - [x] LuxLib
  - [x] Boltz
  - [x] LuxTestUtils
  - [x] WeightInitializers
  - [x] LuxCUDA
  - [x] LuxAMDGPU
  - [x] LuxDeviceUtils
- [x] Proper Versioning
  - [x] Sidebar is not visible for anything apart from `dev` due to redirects from `stable`/`v0.*`
- [x] Import error in the first tutorial https://lux.csail.mit.edu/dev/tutorials/beginner/Basics/main#Automatic%20Differentiation
  - [x] This is from resolving dependencies over already loaded packages. We need to run the literate files in isolated julia runs
- [x] Improve Getting Started Section -- Instead of just the installation instructions put a quick demo there itself
- [x] Right Bar doesn't display current section
  * This is due to the links to sections being generated incorrectly
- [ ] Clickable Tutorial Cards -- This would need some Vue.js knowledge to write custom components. Unless someone does it, it will take me some time to correctly figure it out.
- [x] Setup Google Analytics

**Comment by maxfreu** [comment]
The font is maybe optimal. As mentioned on discourse, comma and period look similar and the @ looks a bit unconventional.

**Comment by avik-pal** [comment]
Font has been updated
