### ISSUE TITLE
Custom Layer, Differential Equation as Activation Function. 

### ISSUE THREAD

**Issue by RohanRajagopal** [LuxDL/Lux.jl#418]
Is there a way to define an activation function using a differential equation to train a recurrent neural network, (sequence $in$, sequence $out$)? 

For instance use the following differential equation as activation function, where input to it is $I_{ext}(t)$, where $I_{ext}(t) = \sum w_{i} x_i(t)$, and gradients are calculated with respect to the weight $W = (w_i)_{i=1}^N$. Essentially akin to a $Dense$ layer but having an ODE define the activation function. 

```julia
using Lux, Random, NNlib, Zygote, Parameters, Plots, SciMLSensitivity, Zygote, BenchmarkTools, ComponentArrays, Lux, Optimisers, DifferentialEquations, DataInterpolations, ForwardDiff

struct Modified_Dense <:  Lux.AbstractExplicitLayer
    # Trainable
    init_W
    init_W_o
end

function Modeified_Dense(W::AbstractArray, W_o::AbstractArray)
    return Hopf(() -> copy(W),() -> copy(W_o))
end

# `W` is a parameter
Lux.initialparameters(::AbstractRNG, layer::Modified_Dense) = (W=layer.init_W(), W_o=layer.init_W_o(),)

rng = Random.default_rng();
model = Modified_Dense(randn(rng, 10), randn(rng, 10))
ps, st = Lux.setup(rng, model)

function (l::Modified_Dense)(x, ps, st)
    p = ComponentArray(ps = ps)
    u0 = ones(10, 2)
    prob_ = remake(prob, u0 = u0, p = p)
    sol = solve(prob_, saveat = time_steps)
    r = sol[:, 1, :]
    theta = sol[:, 2, :]
    out_sub = r .* cos.(theta)
    out = (ps.W' * out_sub)'

    return out, st
end


function Modified_Dense_ODE(du, u, p, t)
    @unpack ps = p
	Iext = ps.W * x_inter_1(t)
    for k in 1:10
        du[k, 1] = u[k, 1] * (1 - u[k, 1]^2) + Iext[k] * cos(u[k, 2])
        du[k, 2] = 1 - Iext[k] * sin(u[k, 2])/u[k, 1]
    end
end

tspan = (0.1, 100.);
time_steps = 1 : 1. : 100;
u = sin.(2*π*time_steps);

x_inter_1 = CubicSpline(u, time_steps);

p = ComponentArray(ps = ps)
u0 = ones(10, 2)
prob = ODEProblem(Modified_Dense_ODE, u0, tspan, p)
sol = solve(prob)

model(x_inter_1, ps, st)                    #This works
```

But the following command errs with an incredibly long error stack trace. 

```
gradient(ps -> sum(first(model(x_inter_1, ps, st))), ps)

```
The following is the error. 
<details>
  <summary>Click to expand</summary>
ERROR: MethodError: no method matching aa_getrf!(::Matrix{ForwardDiff.Dual{ForwardDiff.Tag{ODEFunction{true, SciMLBase.AutoSpecialize, FunctionWrappersWrappers.FunctionWrappersWrapper{Tuple{FunctionWrappers.FunctionWrapper{Nothing, Tuple{Matrix{Float64}, Matrix{Float64}, ComponentVector{Float64, Vector{Float64}, Tuple{Axis{(ps = ViewAxis(1:20, Axis(W = 1:10, W_o = 11:20)),)}}}, Float64}}, FunctionWrappers.FunctionWrapper{Nothing, Tuple{Matrix{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, Matrix{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, ComponentVector{Float64, Vector{Float64}, Tuple{Axis{(ps = ViewAxis(1:20, Axis(W = 1:10, W_o = 11:20)),)}}}, Float64}}, FunctionWrappers.FunctionWrapper{Nothing, Tuple{Matrix{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, Matrix{Float64}, ComponentVector{Float64, Vector{Float64}, Tuple{Axis{(ps = ViewAxis(1:20, Axis(W = 1:10, W_o = 11:20)),)}}}, ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}}, FunctionWrappers.FunctionWrapper{Nothing, Tuple{Matrix{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, Matrix{ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}, ComponentVector{Float64, Vector{Float64}, Tuple{Axis{(ps = ViewAxis(1:20, Axis(W = 1:10, W_o = 11:20)),)}}}, ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 1}}}}, false}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Float64}, Float64, 12}}; ipiv::Vector{Int32}, info::Base.RefValue{Int32})

Closest candidates are:
  aa_getrf!(!Matched::AbstractMatrix{<:Float64}; ipiv, info, check)
   @ LinearSolve ~/.julia/packages/LinearSolve/R5I9Z/src/appleaccelerate.jl:29
  aa_getrf!(!Matched::AbstractMatrix{<:Float32}; ipiv, info, check)
   @ LinearSolve ~/.julia/packages/LinearSolve/R5I9Z/src/appleaccelerate.jl:49

</details>

I was able to set a crude implementation with a single node with a similar ODE as an activation, with support of SciMLSensitivity, by the following, 
```julia
tspan = (0, 200)
time_steps = collect(1:1:10)

function hopf_oscillator(du, u, p, t)
	@unpack W = p
	ω_h = 1.
	μ = 1.
	ω_ext = 1
	I0 = 0.1
	w_rand = rand(5)
	signal = [cos.(i*t) for i in 1:5] 
	Iext = W' * signal
	du[1] = u[1] * (μ - u[1]^2) + I0 * Iext * cos(u[2])
	du[2] = ω_h - I0 * Iext * sin(u[2])/u[1]
end

u0_h = [.1, .1]
p_h = ComponentArray(W = rand(5))

prob_h = ODEProblem(hopf_oscillator, u0_h, dt = 0.1, tspan, p_h)

function gradients_hopf_with_loss_function(p)
	_prob = remake(prob_h, u0 = u0_h, tspan = (0.0, 20.0), p = p)
	sol = solve(_prob, Rosenbrock23(), saveat = time_steps)
	theta = sol[2,:]
        D =  cos.(time_steps)
	r = sol[1, end]
	x = r*cos.(theta) .- D
	sum(abs2, x)  #loss function
end

for i in 1:50
	dp_h = Zygote.gradient(gradients_hopf_with_loss_function, p_h)
	for j in 1:length(p_h)
		p_h[j] = p_h[j] - 0.1 * dp_h[1][j]
	end
end
```

This works (The gradients were calculated and the loss reduced with successive iterations.) I request some suggestions to help fix this error, and atleast understand where I have misinterpreted this Lux implementation. Deeply appreciate any support. Thank you very much.

**Comment by arthur-bizzi** [comment]
I'm not sure I fully understand what you're getting at, but here are some points regarding your code:
- You should definitely _not_ convert your parameters to a ComponentArray inside a layer. Lux layers in general should work the same given parameters in the form of tuples or CAs.
- You're trying to use `prob`  without defining it first. These should probably be a part of your layer struct.
- It's unclear how you intend the data to flow into your layer. If it's in the usual form of a large matrix, then the time vector should probably be separated so it can be fed into the ODE solver. This is connected to the definition of `time-steps`, which you're also missing. I would suggest you think about what you're doing a bit more.
- `Lux.initialstates` should e defined.
- There's a few typos in your code.

**Comment by RohanRajagopal** [comment]
Hey, thank you very ,very much for your helpful comments. Let me work on it a bit more, before I respond with a set of code that I have adapted based on your suggestions. But, let me to try to be more clear in what I hope to do. 

I am trying to implement a layer wherein the activation function of each node is a differential equation; that receives a time series (sequence input), and that is fed to a differential equation system as some sort of external input, (and so acts as the activation function), the ODE is then solved to generate another time series, (sequence output). This is what I did, at least I think I did in this set of code with a "single" node.

```
tspan = (0, 200)
time_steps = collect(1:1:10)

function hopf_oscillator(du, u, p, t)
	@unpack W = p
	ω_h = 1.
	μ = 1.
	ω_ext = 1
	I0 = 0.1
	w_rand = rand(5)
	signal = [cos.(i*t) for i in 1:5] 
	Iext = W' * signal
	du[1] = u[1] * (μ - u[1]^2) + I0 * Iext * cos(u[2])
	du[2] = ω_h - I0 * Iext * sin(u[2])/u[1]
end

u0_h = [.1, .1]
p_h = ComponentArray(W = rand(5))

prob_h = ODEProblem(hopf_oscillator, u0_h, dt = 0.1, tspan, p_h)

function gradients_hopf_with_loss_function(p)
	_prob = remake(prob_h, u0 = u0_h, tspan = (0.0, 20.0), p = p)
	sol = solve(_prob, Rosenbrock23(), saveat = time_steps)
	theta = sol[2,:]
        D =  cos.(time_steps)
	r = sol[1, end]
	x = r*cos.(theta) .- D
	sum(abs2, x)  #loss function
end

for i in 1:50
	dp_h = Zygote.gradient(gradients_hopf_with_loss_function, p_h)
	for j in 1:length(p_h)
		p_h[j] = p_h[j] - 0.1 * dp_h[1][j]
	end
end
```

I hope that makes sense, somewhat. Thank you very much.

**Comment by RohanRajagopal** [comment]
Okay, this seems to work, 

using Lux, DifferentialEquations, Zygote, SciMLSensitivity, Random, ComponentArrays, Parameters, DataInterpolations, Plots

#=

struct Modified_Dense{M <: Lux.AbstractExplicitLayer} <: Lux.AbstractExplicitContainerLayer{(:model,)}
    model::M
    u0
    time_steps 
    solver
    sensealg
    tspan
    kwargs    
end

function Modified_Dense(model::Lux.AbstractExplicitLayer; u0 = 0.1 .* ones(model.out_dims), time_steps = (0.1:1:100), solver=Tsit5(), tspan=(0.0f0, 100.0f0), 
    sensealg=InterpolatingAdjoint(; autojacvec=ZygoteVJP()), kwargs...)
    return Modified_Dense(model, u0, time_steps, solver, sensealg, tspan, kwargs)
end

diffeqsol_to_array(x::ODESolution) = mapreduce(permutedims, vcat, x.u)

function (n::Modified_Dense)(x, ps, st)
    function ODE_Activation(du, u, p, t)
        @unpack ps = p
        for k in 1:n.model.out_dims
            du[k] = k - (ps.weight[k]*x(t) + ps.bias[k])* sin(u[k])
        end
    end

    prob = ODEProblem(ODE_Activation, n.u0, n.tspan, ps)
    sol = diffeqsol_to_array(solve(prob, n.solver, saveat = n.time_steps))
    out = sin.(sol)
    return out, st
end

model = Modified_Dense(Dense(1,10, identity))

rng = Random.default_rng()
Random.seed!(rng, 0)
ps, st = Lux.setup(rng, model)
ps = ComponentArray(ps=ps)
dev = gpu_device()

x = LinearInterpolation(sin.(4 * π * model.time_steps), model.time_steps)

model(x, ps, st)

gradient(ps -> sum(first(model(x, ps, st))), ps)
=#

rng = Random.default_rng()
Random.seed!(rng, 0)

struct Modified_Dense{M <: Lux.AbstractExplicitLayer} <: Lux.AbstractExplicitContainerLayer{(:model,)}
    model::M
    u0
    time_steps 
    solver
    sensealg
    tspan
    kwargs    
end

function Modified_Dense(model::Lux.AbstractExplicitLayer; u0 = 0.1 .* ones(model.out_dims, 2), time_steps = (0.1:0.1:100), solver=Tsit5(), tspan=(0.0f0, 100.0f0), 
    sensealg=InterpolatingAdjoint(; autojacvec=ZygoteVJP()), kwargs...)
    return Modified_Dense(model, u0, time_steps, solver, sensealg, tspan, kwargs)
end

diffeqsol_to_array(x::ODESolution) = mapreduce(permutedims, vcat, x.u)

function (n::Modified_Dense)(x, ps, st)
    function ODE_Activation(du, u, p, t)
        @unpack ps = p
        for k in 1:n.model.out_dims
            du[k, 1] = u[k, 1] * (1 - u[k, 1]^2) + (ps.weight[k]*x(t) + ps.bias[k]) * cos(u[k, 2])
            du[k, 2] = k - (ps.weight[k]*x(t) + ps.bias[k]) * sin(u[k, 2]) / u[k, 1]
        end
    end

    prob = ODEProblem(ODE_Activation, n.u0, n.tspan, ps)
    sol = solve(prob, n.solver, saveat = n.time_steps)
    u1 = sol[:,1,:]
    u2 = sol[:,2,:]
    out = u1.*sin.(u2)
    println(size(out))
    return out, st
end

model = Modified_Dense(Dense(1,10, identity))

ps, st = Lux.setup(rng, model)
ps = ComponentArray(ps=ps)
dev = gpu_device()

x = CubicSpline(sin.(4 * π * model.time_steps), model.time_steps)

model(x, ps, st)

gradient(ps -> sum(first(model(x, ps, st))), ps)

**Comment by RohanRajagopal** [comment]
Okay this seems to work, 

```
using Lux, DifferentialEquations, Zygote, SciMLSensitivity, Random, ComponentArrays, Parameters, DataInterpolations, Plots


rng = Random.default_rng()
Random.seed!(rng, 0)

struct Modified_Dense{M <: Lux.AbstractExplicitLayer} <: Lux.AbstractExplicitContainerLayer{(:model,)}
    model::M
    u0
    time_steps 
    solver
    sensealg
    tspan
    kwargs    
end

function Modified_Dense(model::Lux.AbstractExplicitLayer; u0 = 0.1 .* ones(model.out_dims, 2), time_steps = (0.1:0.1:100), solver=Tsit5(), tspan=(0.0f0, 100.0f0), 
    sensealg=InterpolatingAdjoint(; autojacvec=ZygoteVJP()), kwargs...)
    return Modified_Dense(model, u0, time_steps, solver, sensealg, tspan, kwargs)
end

diffeqsol_to_array(x::ODESolution) = mapreduce(permutedims, vcat, x.u)

function (n::Modified_Dense)(x, ps, st)
    function ODE_Activation(du, u, p, t)
        @unpack ps = p
        for k in 1:n.model.out_dims
            du[k, 1] = u[k, 1] * (1 - u[k, 1]^2) + (ps.weight[k]*x(t) + ps.bias[k]) * cos(u[k, 2])
            du[k, 2] = k - (ps.weight[k]*x(t) + ps.bias[k]) * sin(u[k, 2]) / u[k, 1]
        end
    end

    prob = ODEProblem(ODE_Activation, n.u0, n.tspan, ps)
    sol = solve(prob, n.solver, saveat = n.time_steps)
    u1 = sol[:,1,:]
    u2 = sol[:,2,:]
    out = u1.*sin.(u2)
    println(size(out))
    return out, st
end

model = Modified_Dense(Dense(1,10, identity))

ps, st = Lux.setup(rng, model)
ps = ComponentArray(ps=ps)
dev = gpu_device()

x = CubicSpline(sin.(4 * π * model.time_steps), model.time_steps)

model(x, ps, st)

gradient(ps -> sum(first(model(x, ps, st))), ps)

```

**Comment by avik-pal** [comment]
Closing this since it seems to have been resolved! For future reference, https://discourse.julialang.org/ is a better place for usage-related questions/bugs!
