### ISSUE TITLE
Periodic Padding 

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [LuxDL/Lux.jl#451]
Currently Lux.jl doesn't directly offer the possibility for periodic padding (of e.g. Conv layers). At least I can't see it in neither the code nor documentation. 

It is easy to work around this by using `NNlib.pad_circular` directly, e.g. by: 
```Julia 
nn = Chain(WrappedFunction(x->NNlib.pad_circular(x,1,dims=1:2)), Conv((2,2), 1=>10, relu))
```

I wonder if either this should be either 
* Just mentioned in the doc 
* Or, Actually added as another padding type in the utility functions

**Comment by avik-pal** [comment]
I think a note in the docs should be sufficient!
