### ISSUE TITLE
Adaptors should **not** change the dtype

### ISSUE THREAD

**Issue by YichengDWu** [LuxDL/Lux.jl#462]
The following definition would change `x` of dtype Float64 to `Float32`.
```
adapt_storage(::LuxCUDAAdaptor, x) = cu(x)
```

**Comment by avik-pal** [comment]
Yes, this is expected. For 99% of users, moving data from CPU to GPU would want it to be `Float32` (or whatever is the best choice for that accelerator). The remaining 1% definitely know what they are doing and can make the data Float64 using `|> f64`.
