### ISSUE TITLE
Support for MultiRNNCell

### ISSUE THREAD

**Issue by mchitre** [LuxDL/Lux.jl#472]
It would be nice to have the equivalent of [MultiRNNCell ](https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/rnn_cell/MultiRNNCell) in Lux

**Comment by avik-pal** [comment]
I will take a closer look at this, but I think we can just use Chain. If we can use a chain, we should just add a note in the manual

**Comment by mchitre** [comment]
Chains of this type work:
```julia
Chain(
  Recurrence(RNNCell(inputsize => latentsize); return_sequence=true),
  x -> stack(x; dims=2),
  Recurrence(RNNCell(latentsize => latentsize); return_sequence=true),
  x -> stack(x; dims=2)
      :
)
```

**Comment by avik-pal** [comment]
You might not need a stack here I think. Recurrence should be able to take a VectorOfArray input (this was one of the reasons to not stack the outputs by default)

**Comment by mchitre** [comment]
Yes, I just tested that. I only need the stack at the end to allow a `Dense` layer to take in the output. So:
```
Chain(
  Recurrence(RNNCell(inputsize => latentsize); return_sequence=true),
  Recurrence(RNNCell(latentsize => latentsize); return_sequence=true),
      :
  x -> stack(x; dims=2)
)
```
works.

**Comment by mchitre** [comment]
So just a note in the documentation is good enough for this.
