### ISSUE TITLE
How to choose a specific GPU device

### ISSUE THREAD

**Issue by nighthink** [LuxDL/Lux.jl#480]
If I have more than one GPU device, how do I choose to use one or more of them?
It is like `device0 = Flux.get_device("CUDA", 0) ` (https://fluxml.ai/Flux.jl/stable/gpu/#Data-movement-across-GPU-devices).

**Comment by avik-pal** [comment]
Currently, this is not implemented. The way to do this would be to set the device globally for CUDA using `device!(0)`
