### ISSUE TITLE
ComponentArrays type piracy

### ISSUE THREAD

**Issue by ablaom** [LuxDL/Lux.jl#482]
If you import `Lux` it alters the behaviour of `Functors.functor` on `ComponentArrays`:

```julia
using ComponentArrays, Functors
comp_array = (x=[1.0, 2.0], y=[3.0, 4.0]) |> ComponentArray
julia> Functors.functor(comp_array) |> first
()

using Lux
julia> Functors.functor(comp_array) |> first
(x = [1.0, 2.0], y = [3.0, 4.0])
```

Since Lux.jl does not own `ComponentArrays`, this is type piracy, no?

The offending definition is [here](https://github.com/LuxDL/Lux.jl/blob/1cb774c8cdaeed1b16811ecc41b15b81bb8016f9/ext/LuxComponentArraysExt.jl#L22).

A solution would be be to request ComponentArrays.jl to overload `Functors.functor` for it's types.

**Comment by avik-pal** [comment]
Yeah these need to be upstreamed. ComponentArrays.jl has been very helpful in accepting these patches, so we can move them there itself via extensions.

These were implemented here pre extensions era of julia, so we did not want to burden CAs.jl with dependencies. But now they can be just part of extensions.

**Comment by ablaom** [comment]
Thanks for considering this.

I am also wondering if a recursive form would be more useful or appropriate. Currently, we have:

```julia
julia> using Lux, Functors, ComponentArrays

julia> nt = (x=1, y=(a=2, b=3))
(x = 1, y = (a = 2, b = 3))

julia> ca = ComponentArray(nt);

julia> deconstructed, _ = Functors.functor(ca)
((x = 1, y = (a = 2, b = 3)), ComponentArray)

julia> deconstructed.y
ComponentVector{Int64,SubArray...}(a = 2, b = 3)
```

For my use case, at least, I'd prefer `deconstructed == nt` but maybe that's not the general Functors philosophy, or maybe a recursive version could have unexpected consequences??. A recursive version looks like this:

```julia
_functor(c) = c
_functor(c::ComponentArray) =
    NamedTuple{propertynames(c)}(_functor.(getproperty.((c,), propertynames(c))))
Functors.functor(c::ComponentArray) = _functor(c), ComponentArray
```
