### ISSUE TITLE
AMDGPU CI takes a lot of time

### ISSUE THREAD

**Issue by pxl-th** [LuxDL/Lux.jl#495]
Is it supposed to take this long?
![image](https://github.com/LuxDL/Lux.jl/assets/17990405/125e91e3-33a3-4865-beb5-e8cbccbab10b)

We have only 1 machine (sometimes 2) running AMD GPU CI, so maybe worth putting a timeout?

**Comment by avik-pal** [comment]
It wasn't in 1.9 but the time has gone up in 1.10 not sure why. FWIW the AMD and CUDA tests are identical so I would guess it should take similar times.

Regardless I will put a timeout. 1hr sounds reasonable?

**Comment by avik-pal** [comment]
It is just 1 test process that is stalling so it should be reasonably easy to debug

**Comment by pxl-th** [comment]
> 1hr sounds reasonable?

Yeah, that's fine. 

> It is just 1 test process that is stalling so it should be reasonably easy to debug

Hopefully it isn't one of those Navi 3 related hangs that seem to happen randomly :/

**Comment by pxl-th** [comment]
I suggest limiting number of workers to at max 2 for AMDGPU CI as well.
I've seen hangs because of big number of test workers (just like Lux.jl currently has).

**Comment by avik-pal** [comment]
Thanks, that seems to have done the trick, CI runs in about 15 mins now :tada:. Now I need to do this in all of the downstream testing repos :sweat: https://buildkite.com/julialang/lux-dot-jl/builds/988#018deb7d-1f7e-4d1a-9e68-fa6f3da962d8

**Comment by pxl-th** [comment]
https://github.com/ROCm/HIP/issues/3370#issuecomment-1970744166 might be the reason why it hangs with more workers.
