### ISSUE TITLE
Let @compact return the updated state 

### ISSUE THREAD

**Issue by schlichtanders** [LuxDL/Lux.jl#516]
`@compact` is marvelous! Really great addition to the package.

I just experimented a bit with it, mainly understanding how it handles states (the documentation is not very explicit).
```julia
julia> using Lux, Random

julia> import Lux.Experimental: @compact

julia> MyDense(;d_in=5, d_out=7, act=relu) = @compact(W=randn(d_out, d_in), b=zeros(d_out), incr=1) do x
           y = W * x
           incr *= 10
           return act.(y .+ b) .+ incr
       end
MyDense (generic function with 1 method)

julia> model = MyDense()
@compact(
    W = randn(d_out, d_in),
    b = zeros(d_out),
    incr = 1,
) do x 
    y = W * x
    incr *= 10
    return act.(y .+ b) .+ incr
end       # Total: 42 parameters,
          #        plus 1 states.

julia> ps, st = Lux.setup(Xoshiro(0), model)
((W = [-1.331863896320048 0.848499304071536 … -1.5469896070993128 -0.6639743984242839; 0.23804075742354194 0.03221926586176658 … 1.1751151943266476 0.19227587120451167; … ; 0.4278311333124438 -0.3039318707710832 … 0.6283795021870702 -0.6388152226639742; 0.23504184055362462 0.16601196538094215 … -0.5943343213365917 -0.6776496423340842], b = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), (incr = 1,))

julia> model(ones(5, 10), ps, st)
([10.0 10.0 … 10.0 10.0; 11.94659440368247 11.94659440368247 … 11.94659440368247 11.94659440368247; … ; 10.0 10.0 … 10.0 10.0; 10.0 10.0 … 10.0 10.0], (incr = 1,))
```

As you can see, the `@compact` does not return the updated `incr`, but the initial.

**Comment by avik-pal** [comment]
You are right; I think we do need to be a bit clear about the state handling.

The output here is actually correct (even I thought it was a bug :sweat:). The thing that is happening here is roughly

```julia
(generated function(x, ps, st) -> begin
# Unwrap args. For eg,
incr = st.incr

<user defined function body>
incr *= 10
</user defined function body>

st_ = .... # This happens based on mutated states + StatefulLuxLayers

return <user output>, st_ # `st` 
end
```

**Comment by avik-pal** [comment]
To do what you are asking for, we need to let go of the function barrier and add code into the function body itself, which (Fluxperimental and) I have historically avoided because that solves very few additional cases but leads to massive code complexity.

I did have a tracing-based function to do this at one point, but I could never merge it because it led to bugs that are very hard to detect, and since then I have avoided messing with user code too much.

**Comment by schlichtanders** [comment]
Couldn't you simply add something like

```julia
(generated function(x, ps, st) -> begin
	# Unwrap args. For eg,
	incr = st.incr
	
	<user defined function body>
	incr *= 10
	</user defined function body>
	
	st_ = .... # This happens based on mutated states + StatefulLuxLayers
        
        ######## similar to unwrap above ########
        st_.incr = incr
	# ...
        ##################################

	return <user output>, st_ # `st` 
end
```

**Comment by avik-pal** [comment]
The updated `incr` is not available at `st_`. The user defined function is its own function:

```julia
<user function>(....) -> ret_val

(generated function(x, ps, st) -> begin
	# Unwrap args. For eg,
	incr = st.incr
	
    y = <user function>(...., incr)
	
	st_ = .... # This happens based on mutated states + StatefulLuxLayers
        
        ######## similar to unwrap above ########
        st_.incr = incr  (incr never updated here)
	# ...
        ##################################

	return y, st_ # `st` 
end
```

**Comment by avik-pal** [comment]
actually even that restricts the scope of `incr` so that won't work and without restricting the scope I think we run into Boxing, so the user code will become type unstable

**Comment by schlichtanders** [comment]
My fault, the user code is run inside a function.

For me this looks like introducing the states as additional return values of this function - would this interfere with type stability? Can you explain the boxing problem?
