### ISSUE TITLE
Documentation Request: Have a section about Loss Functions

### ISSUE THREAD

**Issue by schlichtanders** [LuxDL/Lux.jl#517]
I just try to use Lux.jl to have a simple prediction on iris dataset, predicting the Species class. It is a categorical variable and I have no clue how to adapt Lux for it.

I would expect a section in the documentation about Loss functions. Flux actually has one.
I think this would be a great addition to the Lux webpage.

**Comment by avik-pal** [comment]
I think it might be a good idea to have loss functions inbuilt or at least part of the overall Lux ecosystem which is just reexported by Lux similar to WeightInitializers and other libraries

**Comment by schlichtanders** [comment]
I always appreciate efforts to centralize common utilities.
Is there a reason why `LossFunctions.jl` can not be used or extended?

**Comment by avik-pal** [comment]
The other case against LossFunctions would be it tries to be dependency light and hence a lot of its code needs to be Base/LinearAlgebra instead of using the more optimized NNlib versions

**Comment by schlichtanders** [comment]
If there is a performance benefit, it would be great to see it. For know I cannot see where this should come from.

**Comment by avik-pal** [comment]
We have custom dispatches in NNlib to call cudnn and miopen and for some CPU ones we have KA threaded implementations.

**Comment by NeroBlackstone** [comment]
I want to know what is the difficulty with Lux.jl's built-in loss function? It would be more convenient if we had a predefined loss function.

Is it possible to directly copy the loss function implementation of [Flux.jl](https://github.com/FluxML/Flux.jl/blob/master/src/losses/functions.jl)?

**Comment by NeroBlackstone** [comment]
Another similar situation is activation functions. 

Although NNlib.jl provides many activation functions for import (if I understand correctly, this should be the way to use activation functions in Lux.jl), I still think it is necessary for Lux.jl to provide a separate activation function page for reference so that we don’t need to search the NNlib documentation externally, which is exactly [what Flux.jl does](https://fluxml.ai/NNlib.jl/stable/reference/#Activation-Functions).

I can open a PR to implement this, adding API reference of NNlib.

**Comment by avik-pal** [comment]
> Is it possible to directly copy the loss function implementation of [Flux.jl](https://github.com/FluxML/Flux.jl/blob/master/src/losses/functions.jl?rgh-link-date=2024-06-07T18%3A35%3A10Z)?

Mostly but with some specializations on the `agg` functions. Something like

```julia
function lossfn(...; agg::T = mean, ...) where {T}
    res = ....
    return __fast_agg(agg, op, res)
end

@inline __fast_add(::typeof(mean), op, res) = mean(op, res)
@inline __fast_add(::typeof(sum), op, res) = sum(op, res)
@inline __fast_add(agg::F, op, res) where {F} = agg(op.(res))
```

It is possible to fuse the ops a bit more, but this should be fine for now.

> I still think it is necessary for Lux.jl to provide a separate activation function page for reference so that we don’t need to search the NNlib documentation externally

It should just be a link from the sidebar of https://lux.csail.mit.edu/stable/api/Lux/layers similar to how external tutorials are linked from https://lux.csail.mit.edu/stable/tutorials/.

Eventually the idea is to have MultiDocumenter support DocumenterVitepress, then we just have something equivalent to the SciML aggregated docs
