### ISSUE TITLE
Documentation Request: Also list GeometricML.jl and SciML.ai under Ecosystem

### ISSUE THREAD

**Issue by schlichtanders** [LuxDL/Lux.jl#518]
these two appear as "trusted by" in a side pane. It would be great to also see them included in the dedicated ecosystem page

**Comment by avik-pal** [comment]
SciML is already there (most of the repos in ecosystem are SciML ones). GeometricML needs to be added

**Comment by schlichtanders** [comment]
Thank you so much for all these quick adaptations
