### ISSUE TITLE
Should `replicate` be part of LuxCore?

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [LuxDL/Lux.jl#531]
It's my understanding that LuxCore is aimed more at defining the abstract layers, but I feel that `replicate` being such a central part of the Lux philosophy should be included in LuxCore.  Some `initialstates` calls such as the ones for [rnn](https://github.com/LuxDL/Lux.jl/blob/main/src/layers/recurrent.jl#L273) and [dropout](https://github.com/LuxDL/Lux.jl/blob/77a9d76b898c2683b1b3a4ddaa6de0f96ef5861a/src/layers/dropout.jl#L40) use `replicate`, so it would make sense to have it available on LuxCore to build fully compatible layers in external packages

**Comment by avik-pal** [comment]
I agree. I had left it out because I thought we would eventually figure out how to solve #9. But currently, that seems too far off, so we can move it to LuxCore

**Comment by MartinuzziFrancesco** [comment]
Sounds good to me, I guess we can revisit this once something on its way for #9. I can draft a couple of PRs for this issue if it's fine for you
