### ISSUE TITLE
pad=SamePad() does not work as intended in ConvTranspose.

### ISSUE THREAD

**Issue by MatsudaHaruki** [LuxDL/Lux.jl#534]
Hi, this is my first issue. I have originally used Flux.jl, but I like the design policy of Lux.jl and am considering moving to this one. 

Lux.jl's ConvTranspose seems to calculate padding differently than Flux.jl's when SamePad() is specified. My MRE is as follows:

```julia
using Lux, Flux, Random

model_Flux = Flux.ConvTranspose((3,), 2 => 1; pad=Flux.SamePad(), stride=2)
model_Lux = Lux.ConvTranspose((3,), 2 => 1; pad=Lux.SamePad(), stride=2)

ps, st = Lux.setup(Random.default_rng(), model_Lux)

x = randn(Float32, 2, 2, 1)    # size(x) is (2, 2, 1)

y_Flux = model_Flux(x)
y_Lux, st = model_Lux(x, ps, st)

println("size of y_Flux: $(size(y_Flux))")    # shows (4, 1, 1)
println("size of y_Lux: $(size(y_Lux))")      # shows (3, 1, 1), is not as intended
````

Is there something wrong with my code?
Thank you.

**Comment by avik-pal** [comment]
No there is a bug in the handling of SamePad for ConvTranspose. I will fix and tag a release within the next hr.
