### ISSUE TITLE
Stable docs missing

### ISSUE THREAD

**Issue by jariji** [LuxDL/Lux.jl#566]
https://lux.csail.mit.edu/stable/ 404

**Comment by avik-pal** [comment]
it is a redirect issue that is being looked at https://github.com/LuxDL/DocumenterVitepress.jl/issues/81

For now if you click the logo 
![image](https://github.com/LuxDL/Lux.jl/assets/30564094/f366fbe9-2ff3-40c4-8157-1e85899a6097)
from https://lux.csail.mit.edu/stable/ it should redirect correctly

**Comment by avik-pal** [comment]
Fixed with a custom symlink postprocessing
