### ISSUE TITLE
Tutorial links too small

### ISSUE THREAD

**Issue by jariji** [LuxDL/Lux.jl#567]
Only the `</>` is a link, I didn't know where I was supposed to click. It would be easier if the whole box were a link, or its contents.

https://lux.csail.mit.edu/dev/tutorials/

![image](https://github.com/LuxDL/Lux.jl/assets/96840304/94725558-7370-4a21-8db3-ec6b6d82dcf7)

**Comment by avik-pal** [comment]
I agree it would be very nice to have it. That said, my vue & vite skills are extremely bad (almost non-existent).

If someone wants to write a vue component I would gladly accept the PR for it.
