### ISSUE TITLE
Definition and implementation of 'Loss' in Linear Regression Tutorial "Julia & Lux for the Uninitiated"

### ISSUE THREAD

**Issue by CMoebus** [LuxDL/Lux.jl#664]
Thanks for the tutorial, which has in some places a steep learning curve (at least for me ;) ). I had some problems with the definition of  the loss function 'mse' and the implementation of it later.

In the LaTex-formula for the error-sums-of-squares the division is by 1/2. This is an error if you define the mse. It should be 1/N. 
Furthermore later on the function mse is implemented by two methods:
- function mse(model, ps, st, X, y)
    y_pred, st_new = model(X, ps, st)
    return sum(abs2, y_pred .- y), st_new
end
- mse(weight, bias, X, y) = sum(abs2, weight * X .+ bias .- y).

But despite their function name 'mse' they only implement the usual 'ssq' (=sum-of-squares). I think this should be corrected. Besides that is the implementation of the iteration loop a bit opaque. At least for one new to Lux.jl and DL.

Thanks a lot in advance, Claus

**Comment by avik-pal** [comment]
right, they should be `mean(abs2, ...)`. Make a PR?

> Besides that is the implementation of the iteration loop a bit opaque

Do you have specific suggestions for improvement?

**Comment by CMoebus** [comment]
Hi Avik,
I 've made some refactorings within Pluto-notebooks. Because Pluto has a declarative style I introduced some functions. Here are two links. One, to a new t-test with two submodels and the second to the refactored 'linear regression' tutorial. Maybe there are more elegant solutions, but then I need more understanding of the workings of LUX.jl.
- https://uol.de/f/2/dept/informatik/ag/lks/download/Probabilistic_Programming/JULIA/Pluto.jl/Machine_Learning/UnderstandingDeepLearning/PCM20240523_tTestAsLinearRegressionWithLUX.html?v=1716819668
- https://uol.de/f/2/dept/informatik/ag/lks/download/Probabilistic_Programming/JULIA/Pluto.jl/Machine_Learning/UnderstandingDeepLearning/PCM20240520_MultivariateLinearRegressionWithLUX.html?v=1716820720

All the best, Claus
