### ISSUE TITLE
Support for inactive arguments in DifferentiationInterface

### ISSUE THREAD

**Issue by gdalle** [LuxDL/Lux.jl#685]
https://github.com/LuxDL/Lux.jl/blob/44c7df2637a273a0615c85d325a53192d131398f/bench/helpers.jl#L56-L58

Do you think supporting one active and one inactive argument in DI would be enough?

**Comment by avik-pal** [comment]
That comment was from @wsmoses

**Comment by wsmoses** [comment]
I think the bigger issue is the closure. 

So the question is whether DI can construct the same multi-arg multi-activity Enzyme autodiff call, without constructing a closure.

**Comment by gdalle** [comment]
See #311 to continue the discussion
