### ISSUE TITLE
Add documentation about how to partial tests.

### ISSUE THREAD

**Issue by NeroBlackstone** [LuxDL/Lux.jl#701]
It takes too long to fully test Lux.jl! I noticed that I could narrowing the scope of testing by modifying the code in `runtests.jl` or setting the `LUX_TEST_GROUP` environment variable. 

``` julia
const LUX_TEST_GROUP = lowercase(get(ENV, "LUX_TEST_GROUP", "all"))
# replace tag "all"
const LUX_TEST_GROUP = lowercase(get(ENV, "LUX_TEST_GROUP", "core_layers"))
```

It would be nice if there was documentation that explained this, which would greatly reduce testing time.

**Comment by NeroBlackstone** [comment]
> It takes too long to fully test Lux.jl! I noticed that I could test only few items by modifying the code in `runtests.jl` or setting the `LUX_TEST_GROUP` environment variable.
> 
> ```julia
> const LUX_TEST_GROUP = lowercase(get(ENV, "LUX_TEST_GROUP", "all"))
> # replace tag "all"
> const LUX_TEST_GROUP = lowercase(get(ENV, "LUX_TEST_GROUP", "core_layers"))
> ```
> 
> It would be nice if there was documentation that explained this, which would greatly reduce testing time.

**Comment by NeroBlackstone** [comment]
I can add a note to the documentation if needed. But I don't know where I should add it

**Comment by avik-pal** [comment]
I have been meaning to create a `Development Documentation`. For now, it might be worthwhile adding a section in the main README.md about how to run the tests.
