### ISSUE TITLE
Feature Request: Allow recurrent layers with 2D input (features * seq_length), even if the order is BatchLastIndex

### ISSUE THREAD

**Issue by NeroBlackstone** [LuxDL/Lux.jl#767]
Currently RNNCell supports two-dimensional input, but the Recurrence layer does not support two-dimensional input if `ordering=BatchLastIndex()`:

``` julia
using Lux, Random

rng = Random.default_rng()
Random.seed!(rng, 0)
model = Recurrence(GRUCell(3=>6),ordering=BatchLastIndex())
ps, st = Lux.setup(rng, model)
x = rand(Float32,3,4)
y1 = model(x,ps,st)[1]
#ERROR: `BatchLastIndex` not supported for AbstractMatrix. You probably want to use `TimeLastIndex`.
```

Obviously, if the Recurrence layer supports (feature * seq_length) input when `BatchLastIndex`, model inferance will be very convenient, so there is no need to construct an additional Recurrence model with TimeLastIndex() after training.

If you think this is reasonable I can open a PR.

**Comment by NeroBlackstone** [comment]
a workaround is make `reshape(x, Val(3))`, then x will be 3d matrix, and size of last demension is 1

**Comment by avik-pal** [comment]
Yes, it would make sense to treat this as an input with batch size 1.
