### ISSUE TITLE
unexpected parameter type for AbstractExplicitContainer with single trainable field

### ISSUE THREAD

**Issue by CarloLucibello** [LuxDL/Lux.jl#795]
In the following example I was expecting `ps` to have a single field, `x`:
```julia
using Lux 
using Lux: AbstractExplicitContainerLayer
using Random

struct A <: AbstractExplicitContainerLayer{(:x,)}
    x
    y 
end


a = A(Dense(3, 5), true)
rng = Random.default_rng()
ps = Lux.initialparameters(rng, a)
ps.x #ERROR, no field named x
ps.weight # OK
```

Is this the expected behavior?

**Comment by avik-pal** [comment]
This is one (expected) behavior that I simultaneously hate and love.

1. The main con is that it is inconsistent with the behavior you have when the tuple is of `length > 1`.
2. The advantage is that it lets you use things like `DebugLayer` without having to update the parameter structure.

That said, I have been thinking of fixing this behavior in 1.0 release of LuxCore by splitting up the abstract types in `AbstractLuxLayer` and 2 "sub"-abstract types `AbstractLuxContainerLayer` and `AbstractLuxWrapperLayer`. 

* `AbstractLuxWrapperLayer` behaves like the current `AbstractLuxContainerLayer` with single trainable field
* `AbstractLuxContainerLayer` behavior is consistent across all length of the trainable tuple

**Comment by CarloLucibello** [comment]
I think distinguishing a `AbstractLuxWrapperLayer` and a `AbstractLuxContainerLayer` is a good idea

**Comment by avik-pal** [comment]
Tentatively https://github.com/LuxDL/LuxCore.jl/blob/7a622e591bf369e37430f327f458240e6089e2ff/test/runtests.jl#L34-L52 is the version that I am going for.

- Container types will have the behavior that currently errors in the example, i.e. `ps.x` will work but not `ps.weight`.
- The current behavior that you see will be possible via Wrapper type
