### ISSUE TITLE
Add Float128 support

### ISSUE THREAD

**Issue by sandijs-private** [LuxDL/Lux.jl#851]
I recently customized Flux.jl layers code to introduce Float64 support... To enable it back.

Lux.jl could be more superior and support ability to use various floats.

In my use case, Float32 -> Float64 transition demonstrated completely different Neural Network behavior.

Ironically, it was visible, barely, that Float128 is needed.

Looking into the tomorrow, there should be hyper sensitive Neural Networks framework out there.

Especially, for scientific researches.

I know that I can modify the code to fit my use case.

But it will be better if that will be done by some strong mathematician, not me.

**Comment by avik-pal** [comment]
You can convert parameters to 128 bit Floats (`BigFloat`) using `Lux.LuxEltypeAdaptor{BigFloat}`, and use it similar to how `f64`/`f32`/`f16` are used
