### ISSUE TITLE
Is `AbstractLuxContainerLayer` abandoned in Lux 1.0.4?

### ISSUE THREAD

**Issue by disadone** [LuxDL/Lux.jl#942]
I am going through the tutorial:
https://lux.csail.mit.edu/dev/tutorials/beginner/3_SimpleRNN#Creating-a-Classifier

However, julia tell me

```
UndefVarError: `AbstractLuxContainerLayer` not defined

Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:31
 [2] top-level scope
   @ XXX\my_julia_ML_learning\jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_W2sZmlsZQ==.jl:
```

Is the tutorial need to be updated?

It is weird, it only happens in jupyter in vscode. Julia file works fine...

**Comment by avik-pal** [comment]
You are probably running an older version of Lux (jupyter notebook using a different project perhaps?). AbstractLuxContainerLayer was introduced in LuxCore/Lux v1.

The docs are live updated and CI would fail if any of the examples aren't working
